name: CI for Project Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install pandas

    - name: List Files in Project Directory
      run: ls -la ./project

    - name: Run Test Script
      run: bash https://github.com/mhpolas/Data-engineering/blob/main/project/tests.sh
